### ISSUE TITLE
How do I gift you cash for your efforts?

### ISSUE THREAD

**Issue by milljm** [dolkensp/ptYou#8]
Your extension really helps, and I'd like to support what you have accomplished. Is there a way I can do that?

**Comment by peter-dolkens** [comment]
Only thing I ever set up was https://paypal.me/dolkensp

Please keep in mind though, ptYou is not currently in active development. I'm not sure if it's still working, or if CIG have changed the friends APIs again, and I'm not in a position to fire up the game at the moment to check.

Am half way through a move back to Australia, so lots of packing going on.

<3 for your generosity
